"""Telegram delivery bridge for crew reports.

Wires OM pre-flight reports and CEO board reports
to the Chairman via the existing Picoclaw Telegram bridge.
"""

import os, sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def send_om_report(report: dict) -> bool:
    """Send OM pre-flight report to Chairman via Telegram.

    The report is a dict with 'telegram_md' key containing
    evidence-backed markdown (generated by tools/om_tools.py).

    Returns True if sent, False if failed or bridge unavailable.
    """
    if not report:
        return False

    telegram_md = report.get("telegram_md", "")
    if not telegram_md:
        return False

    # Strip markdown heading markers for Telegram readability
    lines = []
    for line in telegram_md.split("\n"):
        # Convert ## Heading to bold text
        if line.startswith("## "):
            line = f"**{line[3:]}**"
        elif line.startswith("# "):
            line = f"**{line[2:]}**"
        elif line == "---":
            line = "—" * 20
        lines.append(line)

    message = "\n".join(lines)

    # Try Picoclaw bridge (Phase 1 — already working)
    try:
        from telegram_bridge import send_telegram

        return send_telegram(message, channel="kubera")
    except Exception:
        pass

    # Fallback: print to stdout (captured by cron → log)
    print(f"[TELEGRAM_WOULD_SEND] {message[:200]}...")
    return False


def send_ceo_board_report(report: dict) -> bool:
    """Send CEO board report to Chairman via Telegram."""
    text = report.get("text", "")
    if not text:
        return False

    try:
        from telegram_bridge import send_telegram

        return send_telegram(text, channel="kubera")
    except Exception:
        print(f"[TELEGRAM_WOULD_SEND] CEO Board Report: {text[:200]}...")
        return False


def send_alert(message: str, channel: str = "kubera") -> bool:
    """Send an urgent alert to Chairman (e.g., SL breach, broker down)."""
    formatted = f"🚨 **ANTARIKSH ALERT** 🚨\n{message}"
    try:
        from telegram_bridge import send_telegram

        return send_telegram(formatted, channel=channel)
    except Exception:
        print(f"[TELEGRAM_WOULD_SEND_ALERT] {message}")
        return False
